Feature/regles gestion
Simplon-hdf/keep-this pull request #5
Opened 2024-05-27 20:12 UTC by Talicke

Adding management rules

2024-05-28 07:04 UTC, Aura974 requested changes
Dans l'ensemble ça me va, juste 2 petites phrases où j'ai besoin de précisions.

2024-05-28 07:04 UTC, Aura974 commented on doc/REGLES-GESTIONS.md
> +- un post-it peut voir son contenu être modifier
- être modifié
 Je ne comprends pas trop le sens de cette tournure. Quelle est la différence avec "un post-it peut être modifié" ?

2024-05-28 07:04 UTC, Aura974 commented on doc/REGLES-GESTIONS.md
> +- un post-it peut avoir un date d’archivage
- une date

2024-05-28 07:04 UTC, Aura974 commented on doc/REGLES-GESTIONS.md
> +- un carnet à un propriétaire
- a un propriétaire ? (du verbe avoir) Ou alors il manque un bout de phrase ?

2024-05-28 07:04 UTC, Aura974 commented on doc/REGLES-GESTIONS.md
> +- un carnet peut avoir un date d’archivage
- une date

2024-05-28 07:04 UTC, Aura974 commented on doc/REGLES-GESTIONS.md
> +- un mot doit avoir un taux de d’utilisation
- taux ~~de~~ d'utilisation

2024-05-28 07:04 UTC, Aura974 commented on doc/REGLES-GESTIONS.md
> +- un mot doit avoir une orthographe
Je ne comprends pas ce qui a voulu être dit par là ?

2024-05-28 07:06 UTC, Talicke commented on doc/REGLES-GESTIONS.md
> +- un post-it peut voir son contenu être modifier
Parce que tu ne peux modifier que son contenu, tu peux pas modifier sa date de création ni son auteur

2024-05-28 07:07 UTC, Talicke commented on doc/REGLES-GESTIONS.md
> +- un post-it peut avoir un date d’archivage
oups

2024-05-28 07:07 UTC, Talicke commented on doc/REGLES-GESTIONS.md
> +- un carnet à un propriétaire
awi

2024-05-28 07:08 UTC, Talicke commented on doc/REGLES-GESTIONS.md
> +- un mot doit avoir une orthographe
Il faut écrire le mot

2024-06-25 09:40 UTC, Aura974 approved these changes

2024-06-25 09:40 UTC, merged